version: '3.8'

services:
  back:
    build: ./back
    ports:
      - ${VITE_APP_API_OUTPUT_PORT}:5000
    env_file:
      - ./.env
    volumes:
      - ./files:/app/files
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13 
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  front:
    build: ./front 
    ports:
      - ${VITE_APP_OUTPUT_PORT}:5173
    env_file: 
      - ./.env
    depends_on:
      - back
