FROM node:20.5.0 as build-stage
WORKDIR /app

ARG VITE_APP_API_OUTPUT_PORT
ENV VITE_APP_API_OUTPUT_PORT $VITE_APP_API_OUTPUT_PORT

COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev"]


# FROM node:lts-alpine

# RUN npm install -g http-server

# WORKDIR /app

# COPY package*.json ./

# RUN npm install

# COPY . .

# RUN npm run build

# EXPOSE 8080

# CMD [ "http-server", "dist" ]